Add documentation for Topology 2.0
thesofproject/sof-docs pull request #380
Opened 2021-11-10 05:42 UTC by ranj063

Add usage documentation for topology 2.0.

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

2021-11-10 15:31 UTC, plbossart requested changes

2021-11-10 15:31 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +		}
it's quite unclear what the difference between instance and index is?

2021-11-10 15:31 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +			# attributes. For ex: "pga.1.1" or "pga.10.2" etc.
use the 10.2 example to explain what is instance and what is index.

2021-11-10 15:31 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +  the object instance.
this is a bit odd because you add the explanations *after* showing an example. I would have put this section earlier.

2021-11-10 15:31 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +  would be constructed as "pga.1.2" where 1 and 2 are the index and instance attribute values.
that answers to my earlier question, so this needs to be moved earlier.

2021-11-10 15:31 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +index attribute is given the value 5.
super unclear.

2021-11-10 15:31 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +  have unique value when multiple PGA objects are instantiated within a pipeline.
but if they are in different pipelines they can have the same instance attribute?

2021-11-19 16:44 UTC, plbossart requested changes
much better indeed, I think I "almost" get it!

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +group and "data" is the class name.
are the class groups to be selected from a predefined list or can they be chosen freely?

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +		type "atring"
typo for string?

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +* Basic attribute qualifiers with the constructor array and unique attribute name. Attribute qualifiers
missing verb in the first sentence?

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +		unique	"name"
in this example, does the constructor and unique attribute need to both use "name", or is it a coincidence?

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +By default, all attributes of type "integer" unless specified otherwise like above. Currently,
missing verb: all attributes are of type "integer"

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +			unique	"instance"
that one is unclear: the instance can be understood as 'the instance within a pipeline' but the comment above hints at a different design 'the instance within a conf file'.

Which is it?

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +			# immutable attributes must be given default values and cannot be modified in the object instance
use may (permission), shall (requirement) and should (recommendation).

do not use 'must' or 'would'.

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +			unique	"instance"
does the compiler detect that the same value is used multiple times?

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +			# deprecated attributes should not be added in the object instance
does the compiler throw a warning if a deprecated attribute it used?

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +				"type"
does the compiler detect if an immutable value is being modified in an object?

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +as hunam reabled string values such as linera, log etc. which are translated to tuple values 0, 1, etc respectively before
hunam reabled string values such as linera 

or rather

human-readable string values such as linear

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +getting added to the tuple array.
not completely following, so the kernel would parse 0..3 and pass the value to firmware without having to deal with an intermediate dictionary with string->integer conversions?

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +where 1 is the value for the unique attribute, "instance", in the pga class definition and the
1 is the value for the unique attribute?

the only thing unique above is 
unique "instance" 

but instance is 5, so what is the 1?

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +attributes should not be modified during object instantiation.
shall

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +Note that the mixer control object has it's name set in the pga widget class definition. But ideally we want to
its

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +giv ethe mixer control a new name whenever a new pga widget object is instantiated. This can be achived as follows:
give the
achieved a

2021-11-19 16:44 UTC, plbossart commented on developer_guides/topology2/topology2.rst
> +			Object.Control.mixer.1 {
what do the ".1" mean or represented in the hierarchy?

maybe we should have an example with multiple objects in the same pipe to show how this works

2021-11-20 05:31 UTC, ranj063 commented
@lgirdwood @juimonen could you please take a look at the documentation. I think I've covered almost everything here

2021-11-22 11:06 UTC, lgirdwood reviewed
@anton-intel @deb-intel this is a large PR, do you guys want to fixup any grammar after merging ?

2021-11-22 13:08 UTC, anton-intel commented
> @anton-intel @deb-intel this is a large PR, do you guys want to fixup any grammar after merging ?
@lgirdwood, yes, we'll create a new PR after merging.

2021-11-25 09:56 UTC, lgirdwood commented
@ranj063 are all comments now resolved ?

2021-12-04 00:04 UTC, ranj063 commented
> @ranj063 are all comments now resolved ?

yes @lgirdwood

2021-12-06 10:25 UTC, lgirdwood approved these changes
@deb-intel @anton-intel fyi.

2021-12-06 10:25 UTC, merged