SOF Zephyr Power Management Architecture documentation
thesofproject/sof-docs pull request #443
Opened 2022-12-12 14:40 UTC by mwasko

2022-12-12 16:07 UTC, lgirdwood approved these changes

2022-12-12 16:10 UTC, lgirdwood commented
@mwasko wondering if there is any clever way we can populate state diagrams from doxygen/code. Would save keeping all aligned.
We should also says what version/platforms the features are supported from (included Zephyr version). @dbaluta I guess you are also NOT fully integrated with Zephyr PM yet ?

2022-12-12 17:40 UTC, deb-intel requested changes
These updates are simple grammatical updates to enhance the flow of your document. They can be merged "as is" into your PR.

2022-12-12 17:40 UTC, deb-intel commented on architectures/firmware/sof-zephyr/rtos_layer/power_management.rst
> +request desired clock and clock power gating if it is necessary for I/O,
```suggestion
request the desired clock and clock power gating if it is necessary for I/O,
```

2022-12-12 17:40 UTC, deb-intel commented on architectures/firmware/sof-zephyr/rtos_layer/power_management.rst
> +For instance, audio I/Os such as I2S associated with audio domain require high
```suggestion
For instance, audio I/Os such as I2S associated with audio domain require a high
```

2022-12-13 07:55 UTC, mwasko commented
> These updates are simple grammatical updates to enhance the flow of your document. They can be merged "as is" into your PR.

@deb-intel thanks. Gramma updates merged and squashed into PR commit.

2022-12-13 14:04 UTC, deb-intel commented
@mwasko Nice job! @lgirdwood are you ready for this to be merged? Do you want to wait on additional responses to earlier questions you had?

2022-12-13 16:54 UTC, mmaka1 approved these changes

2022-12-14 07:06 UTC, merged