rtos: io_drivers: add loopback mode description
thesofproject/sof-docs pull request #490
Opened 2024-03-13 12:01 UTC by marcinszkudlinski

This commit adds a description of using SSP devices in loopback mode

2024-03-13 16:02 UTC, plbossart commented on architectures/firmware/sof-zephyr/rtos_layer/io_drivers/i2s/i2s_driver.rst
> +the Tx pin of the transmitter is connected to the Rx pin of the receiver.
that's not quite right. The connection is at the IP level, not at the physical data pins. We can enable the loopback even if the pins are not connected to anything, e.g. on an Up board or RVP.

2024-03-14 13:13 UTC, plbossart approved these changes

2024-03-15 08:02 UTC, mwasko submitted a review, later dismissed

2024-03-15 16:16 UTC, plbossart submitted a review, later dismissed

2024-03-18 21:29 UTC, deb-intel requested changes
Edits made to improve style and readability.

2024-03-18 21:29 UTC, deb-intel commented on architectures/firmware/sof-zephyr/rtos_layer/io_drivers/i2s/i2s_driver.rst
> +I2S transmitter and receiver share data pins at IP level - the Tx pin of the transmitter
```suggestion
The I2S transmitter and receiver share data pins at the IP level. The Tx pin of the transmitter 
```

2024-03-18 21:29 UTC, deb-intel commented on architectures/firmware/sof-zephyr/rtos_layer/io_drivers/i2s/i2s_driver.rst
> +Please note that
```suggestion
Please note the following: 
```

2024-03-18 21:29 UTC, deb-intel commented on architectures/firmware/sof-zephyr/rtos_layer/io_drivers/i2s/i2s_driver.rst
> + - all the parameters of transmitter and receiver, like number of channels, data rates
```suggestion
 - all the parameters of transmitter and receiver, like number of channels, data rates, and format must match each other
```

2024-03-18 21:29 UTC, deb-intel commented on architectures/firmware/sof-zephyr/rtos_layer/io_drivers/i2s/i2s_driver.rst
> +and format, must match each other
```suggestion

```

2024-04-15 14:08 UTC, lgirdwood approved these changes

2024-04-15 14:09 UTC, lgirdwood commented
Applied @deb-intel changes, pending CI.

2024-04-15 14:34 UTC, merged